Repository Akkkiri/CoGen, pull requests merged in 2023-04, with the labels that each got.

#6 feat: oauth 로그인 및 회원가입
  fe/.env
  fe/.env.development
  fe/.env.production
  fe/public/images/level1.png
  fe/src/api/authAPI.ts
  fe/src/components/BackBtn.tsx
  fe/src/components/CommentContainer.tsx
  fe/src/components/Layout/Header.tsx
  fe/src/components/Layout/RoutesComponent.tsx
  fe/src/components/Layout/ScrollTopBtn.tsx
  fe/src/components/Main/MainUser.tsx
  fe/src/components/Pagenation.tsx
  fe/src/components/PostContainer.tsx
  fe/src/components/QnaContainer.tsx
  fe/src/components/signup/OauthBtn.tsx
  fe/src/components/signup/SelfQnaComponent.tsx
  fe/src/components/user/BookmarkBtn.tsx
  fe/src/components/user/Friend.tsx
  fe/src/components/user/Level.tsx
  fe/src/components/user/UserProfile.tsx
  fe/src/index.css
  fe/src/page/Home.tsx
  fe/src/page/login/Login.tsx
  fe/src/page/login/OauthLogin.tsx
  fe/src/page/mypage/MyBookmark.tsx
  fe/src/page/mypage/MyComment.tsx
  fe/src/page/mypage/MyEdit.tsx
  fe/src/page/mypage/MyFriend.tsx
  fe/src/page/mypage/MyPost.tsx
  fe/src/page/mypage/MyQna.tsx
  fe/src/page/mypage/MyQuestion.tsx
  fe/src/page/mypage/Mypage.tsx
  fe/src/page/post/PostDetail.tsx
  fe/src/page/signup/Info.tsx
  fe/src/page/signup/Nickname.tsx
  fe/src/page/signup/SelfQna.tsx
  fe/src/page/signup/Signup.tsx
  fe/src/store/modules/authSlice.ts
  fe/src/store/store.ts
Labels: feat, 세린

#9 EWHA-11 feat: 퀴즈 구현
  fe/public/images/quiz0.png
  fe/public/images/quiz100.png
  fe/public/images/quiz20.png
  fe/public/images/quiz40.png
  fe/public/images/quiz60.png
  fe/public/images/quiz80.png
  fe/src/components/quiz/LinearBar.tsx
  fe/src/components/quiz/QuizBtn.tsx
  fe/src/components/quiz/QuizScore.tsx
  fe/src/page/Quiz.tsx
  fe/src/store/modules/quizSlice.ts
  fe/src/store/store.ts
Labels: feat, 세린

#15 feat: 알림 구독 신청 및 스타일 제작
  fe/src/api/authAPI.ts
  fe/src/components/Layout/Header.tsx
  fe/src/components/Layout/NotifyModal.tsx
  fe/src/components/Layout/RoutesComponent.tsx
  fe/src/components/Layout/SearchModal.tsx
  fe/src/components/user/NotifyContainer.tsx
  fe/src/components/user/UserProfile.tsx
  fe/src/page/login/IdentityVerification.tsx
  fe/src/page/mypage/MyEdit.tsx
  fe/src/page/mypage/MyEditPassword.tsx
  fe/src/page/mypage/Mypage.tsx
Labels: feat, 세린

#20 EWHA-12 feat: 게시글 및 유저 검색
  fe/package-lock.json
  fe/package.json
  fe/src/api/authAPI.ts
  fe/src/asset/logo.png
  fe/src/components/Layout/Header.tsx
  fe/src/components/Layout/RoutesComponent.tsx
  fe/src/components/Layout/SearchModal.tsx
  fe/src/components/Main/MainUser.tsx
  fe/src/components/PostContainer.tsx
  fe/src/components/QnaContainer.tsx
  fe/src/components/quiz/QuizBtn.tsx
  fe/src/components/user/BookmarkBtn.tsx
  fe/src/components/user/Friend.tsx
  fe/src/components/user/Level.tsx
  fe/src/components/user/UserInfo.tsx
  fe/src/components/user/UserProfile.tsx
  fe/src/index.css
  fe/src/page/Home.tsx
  fe/src/page/login/OauthLogin.tsx
  fe/src/page/mypage/MyComment.tsx
  fe/src/page/mypage/MyEdit.tsx
  fe/src/page/mypage/MyQna.tsx
  fe/src/page/mypage/MyQnaEdit.tsx
  fe/src/page/mypage/Mypage.tsx
  fe/src/page/post/Post.tsx
  fe/src/page/search/PostSearch.tsx
  fe/src/page/search/UserSearch.tsx
  fe/src/store/modules/searchSlice.ts
  fe/src/store/store.ts
Labels: feat, style, 세린

#22 chore: 주석 제거
  fe/src/page/login/OauthLogin.tsx
Labels: chore, 세린

#30 삭제, 이미지 업로드 구현중(현재 1개 업로드는 가능)
  fe/src/components/CategorySwiper.tsx
  fe/src/components/CommentContainer.tsx
  fe/src/components/Image.tsx
  fe/src/components/ImageCarousel.tsx
  fe/src/components/ImageUpload.tsx
  fe/src/components/Layout/Header.tsx
  fe/src/components/Main/BestPost.tsx
  fe/src/components/PostDetailContainer.tsx
  fe/src/components/QuestionCommentContainer.tsx
  fe/src/page/mypage/MyComment.tsx
  fe/src/page/post/PostDetail.tsx
  fe/src/page/post/Writepost.tsx
Labels: 유미

#33 fix: 404 에러 처리, add: 알림 url 추가
  fe/src/components/Layout/NotifyModal.tsx
  fe/src/components/user/Friend.tsx
  fe/src/components/user/NotifyContainer.tsx
  fe/src/page/Home.tsx
  fe/src/page/Question/GoneDetail.tsx
  fe/src/page/Question/Question.tsx
  fe/src/page/Quiz.tsx
  fe/src/page/mypage/Mypage.tsx
  fe/src/page/post/Post.tsx
  fe/src/page/post/PostDetail.tsx
  fe/src/page/userpage/Userpage.tsx
Labels: feat, 세린

#38 fix: 이미지 업로드 수정
  fe/src/components/ImageUpload.tsx
  fe/src/components/Layout/Header.tsx
  fe/src/index.css
  fe/src/page/post/EditPost.tsx
  fe/src/page/post/Writepost.tsx
Labels: fix, 세린

#40 add: postSlice 추가
  fe/src/components/Pagenation.tsx
  fe/src/components/SearchCategorySwiper.tsx
  fe/src/components/SelectBox.tsx
  fe/src/page/post/PostDaily.tsx
  fe/src/page/post/PostEtc.tsx
  fe/src/page/post/PostHumor.tsx
  fe/src/page/post/PostPlace.tsx
  fe/src/page/post/PostQuote.tsx
  fe/src/page/post/PostTip.tsx
  fe/src/page/post/PostWorry.tsx
  fe/src/page/post/Writepost.tsx
  fe/src/page/search/PostSearch.tsx
  fe/src/store/modules/postSlice.ts
  fe/src/store/store.ts
  fe/src/util/SelectUtil.ts
Labels: fix, 세린

#54 feat : 이번주 질문 유저 정보 추가 style: 베너 이미지 추가 스와이퍼 수정
  fe/src/asset/banner.png
  fe/src/components/ WarningBtn.tsx
  fe/src/components/CategorySwiper.tsx
  fe/src/components/GoneComment.tsx
  fe/src/components/Main/MainUser.tsx
  fe/src/components/QuestionCommentContainer.tsx
  fe/src/components/SearchCategorySwiper.tsx
  fe/src/components/SelectBox.tsx
  fe/src/page/Home.tsx
  fe/src/page/Question/GoneDetail.tsx
  fe/src/page/Question/Question.tsx
  fe/src/page/post/Post.tsx
  fe/src/page/post/PostDetail.tsx
  fe/src/page/post/Writepost.tsx
  fe/src/util/CategoryUtil.tsx
  fe/src/util/SelectUtil.ts
Labels: feat, style, 유미

#55 style: nav 이름 변경
  fe/package-lock.json
  fe/package.json
  fe/src/App.tsx
  fe/src/api/authAPI.ts
  fe/src/api/axios.ts
  fe/src/asset/logo_2.png
  fe/src/asset/notfound.png
  fe/src/components/Layout/Header.tsx
  fe/src/components/Layout/Nav.tsx
  fe/src/components/Main/BestPost.tsx
  fe/src/components/Main/MainQnaContainer.tsx
  fe/src/components/Main/MainQuizContainer.tsx
  fe/src/components/Main/MainUser.tsx
  fe/src/components/user/Level.tsx
  fe/src/page/Home.tsx
  fe/src/page/NotFound.tsx
  fe/src/page/Question/Question.tsx
  fe/src/page/Quiz.tsx
  fe/src/page/mypage/Mypage.tsx
  fe/src/page/post/Post.tsx
  fe/src/page/post/PostDetail.tsx
  fe/src/util/useDidMountEffect.ts
Labels: style, chore, 세린
